
const alimentos= [


  
 
    {
      nome: "Canelone de ricota com molho branco",
      quantidade: "1 unidade",
      peso: "30 g",
      calorias: 127
    },
    {
      nome: "Capelete de carne com molho de tomate",
      quantidade: "1 col. de servir",
      peso: "45 g",
      calorias: 141
    },
    {
      nome: "Capelete de frango com molho rosê",
      quantidade: "1 col. de servir",
      peso: "45 g",
      calorias: 176
    },
    {
      nome: "Lasanha à bolonhesa com molho branco “Sadia”",
      quantidade: "1 pedaço grande",
      peso: "325 g",
      calorias: 343
    },
    {
      nome: "Lasanha de queijo e presunto",
      quantidade: "1 pedaço médio",
      peso: "150 g",
      calorias: 256
    },
    {
      nome: "Lasanha quatro queijos",
      quantidade: "1 pedaço médio",
      peso: "150 g",
      calorias: 257
    },
    {
      nome: "Macarrão à putanesca (molho de tomate, azeitona preta e aliche ou alcaparras)",
      quantidade: "1 prato fundo",
      peso: "200 g",
      calorias: 290
    },
    {
      nome: "Macarrão alho e óleo",
      quantidade: "1 prato fundo",
      peso: "200 g",
      calorias: 438
    },
    {
      nome: "Macarrão ao sugo",
      quantidade: "1 prato fundo",
      peso: "200 g",
      calorias: 274
    },
    {
      nome: "Macarrão com molho bolonhesa",
      quantidade: "1 prato fundo",
      peso: "200 g",
      calorias: 302
    },
    {
      nome: "Macarrão com molho branco, ervilha e presunto",
      quantidade: "1 prato fundo",
      peso: "200 g",
      calorias: 438
    },
    {
      nome: "Macarrão instantâneo sabor carne “Maggi”",
      quantidade: "1 pacote",
      peso: "85 g",
      calorias: 376
    },
    {
      nome: "Macarrão instantâneo sabor galinha caipira light “Nissin”",
      quantidade: "1 pacote",
      peso: "88 g",
      calorias: 261
    },
    {
      nome: "Macarrão instantâneo sabor quatro queijo “Nissin”",
      quantidade: "1 pacote",
      peso: "88 g",
      calorias: 399
    },
    {
      nome: "Nhoque à bolonhesa",
      quantidade: "1 col. de servir",
      peso: "65 g",
      calorias: 200
    },
    {
      nome: "Panqueca de carne",
      quantidade: "1 unidade média",
      peso: "80 g",
      calorias: 229
    },
    {
      nome: "Pasta com champignon e ervas “Maggi”",
      quantidade: "1 prato raso",
      peso: "90 g",
      calorias: 318
    },
    {
      nome: "Pasta com molho de tomate e bacon “Maggi”",
      quantidade: "1 prato raso",
      peso: "90 g",
      calorias: 339
    },
    {
      nome: "Penne ao funghi “Pastarotti”",
      quantidade: "1 prato raso",
      peso: "88 g",
      calorias: 306
    },
    {
      nome: "Quiche de alho poró “Melhor Bocado”",
      quantidade: "1 unidade",
      peso: "120 g",
      calorias: 329
    },
    {
      nome: "Quiche de frango “Melhor Bocado”",
      quantidade: "1 unidade",
      peso: "120 g",
      calorias: 336
    },
    {
      nome: "Quiche de queijo “Sadia”",
      quantidade: "1 fatia",
      peso: "113 g",
      calorias: 357
    },
    {
      nome: "Quiche de queijo e bacon “Melhor Bocado”",
      quantidade: "1 unidade",
      peso: "120 g",
      calorias: 357
    },
    {
      nome: "Raviole de carne com molho de tomate",
      quantidade: "1 col. de servir",
      peso: "45 g",
      calorias: 156
    },
    {
      nome: "Raviole de queijo com molho branco",
      quantidade: "1 col. de servir",
      peso: "45 g",
      calorias: 174
    },
    {
      nome: "Torta de frango com catupiry “Sadia”",
      quantidade: "1 fatia",
      peso: "125 g",
      calorias: 399
    },
    {
      nome: "Torta de palmito “Sadia”",
      quantidade: "1 fatia",
      peso: "125 g",
      calorias: 392
    },
    {
      nome: "Torta de palmito com catupiry com massa de iogurte “Sadia”",
      quantidade: "1 fatia",
      peso: "125 g",
      calorias: 317
    },
    {
      nome: "Torta de peito de peru “Sadia”",
      quantidade: "1 fatia",
      peso: "125 g",
      calorias: 414
    },
    {
      nome: "Torta de presunto e queijo “Melhor Bocado”",
      quantidade: "1 unidade",
      peso: "120 g",
      calorias: 319
    },

      { nome: "Biscoito “Club social”", quantidade: "1 pacote", peso: "26 g", calorias: 121 },
      { nome: "Biscoito água e gergelim “Piraquê”", quantidade: "4 unidades", peso: "30 g", calorias: 135 },
      { nome: "Biscoito aveia e mel “Nestlé”", quantidade: "5 unidades", peso: "30 g", calorias: 134 },
      { nome: "Biscoito de água light “Piraquê”", quantidade: "16 unidades", peso: "40 g", calorias: 170 },
      { nome: "Biscoito de leite passatempo “Nestlé”", quantidade: "5 unidades", peso: "30 g", calorias: 134 },
      { nome: "Biscoito de fibra", calorias: 135 },
      { nome: "Biscoito de polvilho doce “Cassini”", quantidade: "25 unidades", peso: "30 g", calorias: 141 },
      { nome: "Biscoito de polvilho salgado “Cassini”", quantidade: "25 unidades", peso: "30 g", calorias: 138 },
      { nome: "Biscoito de presunto “Piraquê”", quantidade: "65 unidades", peso: "30 g", calorias: 151 },
      { nome: "Biscoito de queijo “Piraquê”", quantidade: "65 unidades", peso: "30 g", calorias: 105 },
      { nome: "Biscoito integral “Club social”", quantidade: "1 pacote", peso: "26 g", calorias: 118 },
      { nome: "Biscoito magic toast “Marilan”", quantidade: "7 unidades", peso: "25 g", calorias: 94 },
      { nome: "Biscoito magic toast integral “Marilan”", quantidade: "7 unidades", peso: "28 g", calorias: 103 },
      { nome: "Biscoito recheado de chocolate diet “Doce Vita”", quantidade: "3 unidades", peso: "30 g", calorias: 120 },
      { nome: "Biscoito recheado galak “Nestlé”", quantidade: "2 e 1/2 unidades", peso: "30 g", calorias: 146 },
      { nome: "Biscoito recheado passatempo “Nestlé”", quantidade: "2 e 1/2 unidades", peso: "30 g", calorias: 145 },
      { nome: "Biscoito recheado sabor tomate “Club Social”", quantidade: "1 pacote", peso: "28 g", calorias: 139 },
      { nome: "Biscoito roladinho de goiaba “Piraquê”", quantidade: "3 unidades", peso: "30 g", calorias: 136 },
      { nome: "Biscoito tortine de coco “Triunfo”", quantidade: "5 unidades", peso: "30 g", calorias: 150 },
      { nome: "Biscoito tortinhas de chocolate com avelã “Adria”", quantidade: "4 unidades", peso: "30 g", calorias: 148 },
      { nome: "Biscoito tortinhas de limão “Adria”", quantidade: "4 unidades", peso: "30 g", calorias: 146 },
      { nome: "Biscoito wafer de chocolate “Bauducco”", quantidade: "3 e 1/2 unidades", peso: "30 g", calorias: 156 },
      { nome: "Biscoito wafer de chocolate light “Bauducco”", quantidade: "3 e 1/2 unidades", peso: "30 g", calorias: 170 },
      { nome: "Biscoito wafer de morango “Nestlé”", quantidade: "4 e 1/2 unidades", peso: "30 g", calorias: 161 },
      { nome: "Bolacha água e sal “Tostines”", quantidade: "6 unidades", peso: "30 g", calorias: 130 },
      { nome: "Bolacha Champanhe “Bauducco”", quantidade: "3 e 1/2 unidades", peso: "30 g", calorias: 119 },
      { nome: "Bolacha cream craker “Bauducco”", quantidade: "6 e 1/2 unidades", peso: "30 g", calorias: 130 },
      { nome: "Bolacha cream craker integral “Bauducco”", quantidade: "6 e 1/2 unidades", peso: "30 g", calorias: 130 },
      { nome: "Bolacha cream craker light “Bauducco”", quantidade: "6 e 1/2 unidades", peso: "30 g", calorias: 106 },
      { nome: "Bolacha de banana e canela “Bauducco”", quantidade: "6 unidades", peso: "30 g", calorias: 149 },
      { nome: "Bolacha de coco “Bauducco”", quantidade: "6 unidades", peso: "30 g", calorias: 149 },
      { nome: "Bolacha de leite “Bauducco”", quantidade: "6 unidades", peso: "30 g", calorias: 146 },
      { nome: "Bolacha maisena “Adria”", quantidade: "6 unidades", peso: "30 g", calorias: 134 },
      { nome: "Bolacha maria “Piraquê”", quantidade: "8 unidades", peso: "40 g", calorias: 170 },
      { nome: "Bolacha recheada de chocolate “Bono”", quantidade: "3 unidades", peso: "30 g", calorias: 142 },
      { nome: "Bolacha recheada de doce de leite “Bono”", quantidade: "3 unidades", peso: "30 g", calorias: 147 },
      { nome: "Bolacha recheada de morango “Adria”", quantidade: "3 unidades", peso: "30 g", calorias: 148 },
      { nome: "Bolacha recheada negresco “Nestlé”", quantidade: "3 unidades", peso: "30 g", calorias: 141 },
      { nome: "Cookie com gotas de chocolate “Nabisco”", quantidade: "2 unidades", peso: "30 g", calorias: 148 },
      { nome: "Cookie integral de frutas cítricas “Jasmine”", quantidade: "5 unidades", peso: "30 g", calorias: 127 },
      { nome: "Cookie integral diet de cappuccino e avelã “Jasmine”", quantidade: "8 unidades", peso: "30 g", calorias: 119 },
      { nome: "Flocos de arroz caramelizado “Okoshi”", quantidade: "2 unidades", peso: "30 g", calorias: 107 },
      { nome: "Mini biscoito de pizza “Club Social”", quantidade: "50 unidades", peso: "50 g", calorias: 224 },
      { nome: "Rosquinha de leite “Mabel”", quantidade: "6 unidades", peso: "30 g", calorias: 129 },
    
        { nome: "Amido de milho “Maizena”", quantidade: "2 col. sopa", peso: "22 g", calorias: 76 },
        { nome: "Arroz à grega", quantidade: "1 col. sopa", peso: "13 g", calorias: 18 },
        { nome: "Arroz branco cozido", quantidade: "1 col. sopa", peso: "31 g", calorias: 36 },
        { nome: "Arroz integral cozido", quantidade: "1 col. sopa", peso: "31 g", calorias: 34 },
        { nome: "Aveia (farinha) “Quaker”", quantidade: "1/2 xic. chá", peso: "50 g", calorias: 180 },
        { nome: "Aveia em flocos “Quaker”", quantidade: "2 col. sopa", peso: "30 g", calorias: 140 },
        { nome: "Cereal Matinal Fibre 1 “Nestlé”", quantidade: "3/4 xic. chá", peso: "40 g", calorias: 86 },
        { nome: "Cereal nescau “Nestlé”", quantidade: "3/4 xic. chá", peso: "30 g", calorias: 116 },
        { nome: "Corn Flakes “Kellogg’s”", quantidade: "1 xic. chá", peso: "30 g", calorias: 110 },
        { nome: "Creme de arroz “Yoki”", quantidade: "2 e 1/2 col. sopa", peso: "22 g", calorias: 74 },
        { nome: "Farinha de mandioca torrada “Yoki”", quantidade: "1/4 xic. chá", peso: "40 g", calorias: 135 },
        { nome: "Farinha de milho “Yoki”", quantidade: "1/2 xic. chá", peso: "40 g", calorias: 146 },
        { nome: "Farinha de rosca “Yoki”", quantidade: "3 col. sopa", peso: "30 g", calorias: 112 },
        { nome: "Farinha de trigo “Dona Benta”", quantidade: "1/2 xic. chá", peso: "50 g", calorias: 180 },
        { nome: "Farinha láctea “Nestlé”", quantidade: "4 col. sopa", peso: "30 g", calorias: 119 },
        { nome: "Farofa de linhaça com passas e damasco seco", quantidade: "1 col. sopa", peso: "25 g", calorias: 105 },
        { nome: "Farofa de mandioca pronta “Yoki”", quantidade: "1 col. sopa", peso: "35 g", calorias: 144 },
        { nome: "Farofa de mandioca com bacon", quantidade: "1 col. sopa", peso: "35 g", calorias: 161 },
        { nome: "Farofa de soja pronta “Yoki”", quantidade: "1 col. sopa", peso: "35 g", calorias: 149 },
        { nome: "Fécula de batata “Yoki”", quantidade: "2 col. sopa", peso: "20 g", calorias: 70 },
        { nome: "Fubá de milho “Yoki”", quantidade: "1/2 xic. chá", peso: "40 g", calorias: 136 },
        { nome: "Gérmen de trigo “Mãe Terra”", quantidade: "1 col. sopa", peso: "10 g", calorias: 30 },
        { nome: "Granola “Kellogg’s”", quantidade: "1/2 xic. chá", peso: "40 g", calorias: 138 },
        { nome: "Linhaça “Mãe Terra”", quantidade: "1 col. sopa", peso: "10 g", calorias: 45 },
        { nome: "Milho (espiga)", quantidade: "1 unidade", peso: "100 g", calorias: 132 },
        { nome: "Milho em conserva “Etti”", quantidade: "1 xic. chá", peso: "130 g", calorias: 103 },
        { nome: "Mucilon de arroz “Nestlé”", quantidade: "3 col. sopa", peso: "21 g", calorias: 79 },
        { nome: "Mucilon de milho “Nestlé”", quantidade: "3 col. sopa", peso: "21 g", calorias: 79 },
        { nome: "Musli “Casino”", quantidade: "1/2 xic. chá", peso: "30 g", calorias: 126 },
        { nome: "Polentina “Quaker”", quantidade: "1/2 xic. chá", peso: "45 g", calorias: 147 },
        { nome: "Polvilho azedo “Yoki”", quantidade: "2 e 1/2 col. sopa", peso: "20 g", calorias: 69 },
        { nome: "Polvilho doce “Yoki”", quantidade: "2 e 1/2 col. sopa", peso: "20 g", calorias: 71 },
        { nome: "Quinua real em grão “Mãe Terra”", quantidade: "1/4 xic. chá", peso: "45 g", calorias: 179 },
        { nome: "Sucrilhos “Kellogg’s”", quantidade: "3/4 xic. chá", peso: "30 g", calorias: 114 },
        { nome: "Tapioca “Yoki”", quantidade: "2 e 1/2 col. sopa", peso: "30 g", calorias: 105 },
        { nome: "Trigo para kibe “Yoki”", quantidade: "1/3 xic.", peso: "50 g", calorias: 155 },
      
          { nome: "Bisnaguinha “Seven Boys”", quantidade: "1 unidade", peso: "20 g", calorias: 59 },
          { nome: "Ciabatta", quantidade: "1 unidade grande", peso: "80 g", calorias: 247 },
          { nome: "Croissant de queijo", quantidade: "1 unidade grande", peso: "80 g", calorias: 328 },
          { nome: "Croissant simples", quantidade: "1 unidade grande", peso: "67 g", calorias: 276 },
          { nome: "Pão alemão “Wickbold”", quantidade: "1 fatia", peso: "72 g", calorias: 125 },
          { nome: "Pão com canela e passas “Nutrella”", quantidade: "1 fatia", peso: "25 g", calorias: 71 },
          { nome: "Pão de alho na brasa", quantidade: "1 unidade", peso: "50 g", calorias: 187 },
          { nome: "Pão de batata com catupiry", quantidade: "1 unidade", peso: "70 g", calorias: 190 },
          { nome: "Pão de batata simples", quantidade: "1 unidade", peso: "50 g", calorias: 137 },
          { nome: "Pão de centeio “Nutrella”", quantidade: "1 fatia", peso: "25 g", calorias: 61 },
          { nome: "Pão de coco “Panco”", quantidade: "1 fatia grande", peso: "50 g", calorias: 159 },
          { nome: "Pão de forma “Pullman”", quantidade: "1 fatia", peso: "25 g", calorias: 62 },
          { nome: "Pão de forma integral linhaça “Pullman”", quantidade: "1 fatia", peso: "25 g", calorias: 61 },
          { nome: "Pão de forma light “Nutrella”", quantidade: "1 fatia", peso: "17 g", calorias: 36 },
          { nome: "Pão de forma sem casca “Wickbold”", quantidade: "1 fatia", peso: "17 g", calorias: 43 },
          { nome: "Pão de hambúrguer", quantidade: "1 unidade", peso: "50 g", calorias: 177 },
          { nome: "Pão de hambúrguer com gergelim", quantidade: "1 unidade", peso: "50 g", calorias: 188 },
          { nome: "Pão de hot dog", quantidade: "1 unidade", peso: "50 g", calorias: 133 },
          { nome: "Pão de milho “Panco”", quantidade: "1 fatia grande", peso: "40 g", calorias: 120 },
          { nome: "Pão de queijo coquetel “Forno de Minas”", quantidade: "1 unidade", peso: "25 g", calorias: 71 },
          { nome: "Pão de queijo coquetel light “Forno de Minas”", quantidade: "1 unidade", peso: "14 g", calorias: 30 },
          { nome: "Pão de queijo recheado com requeijão “Forno de Minas”", quantidade: "1 unidade", peso: "27 g", calorias: 74 },
          { nome: "Pão de soja light “Pullman”", quantidade: "1 fatia", peso: "25 g", calorias: 49 },
          { nome: "Pão francês", quantidade: "1 unidade", peso: "50 g", calorias: 135 },
          { nome: "Pão francês integral", quantidade: "1 unidade", peso: "50 g", calorias: 135 },
          { nome: "Pão francês sem miolo", quantidade: "1 unidade", peso: "30 g", calorias: 75 },
          { nome: "Pão integral sem casca light “Wickbold”", quantidade: "1 fatia", peso: "14 g", calorias: 29 },
          { nome: "Pão italiano", quantidade: "1 fatia", peso: "40 g", calorias: 137 },
          { nome: "Pão preto “Nutrella”", quantidade: "1 fatia", peso: "28 g", calorias: 70 },
          { nome: "Pão sírio", quantidade: "1 unidade grande", peso: "50 g", calorias: 180 },
          { nome: "Pão sovado “Seven Boys”", quantidade: "1 fatia", peso: "50 g", calorias: 156 },
          { nome: "Pão sueco", quantidade: "", peso: "30 g", calorias: 100 },
          { nome: "Torrada canapé “Bauducco”", quantidade: "9 unidades", peso: "30 g", calorias: 119 },
          { nome: "Torrada de alecrim com azeite “In Citta”", quantidade: "3 unidades", peso: "15 g", calorias: 78 },
          { nome: "Torrada de alho “Flório”", quantidade: "6 unidades", peso: "30 g", calorias: 122 },
          { nome: "Torrada integral “Bauducco”", quantidade: "3 unidades", peso: "30 g", calorias: 116 },
          { nome: "Torrada salgada “Bauducco”", quantidade: "3 unidades", peso: "30 g", calorias: 119 },
          { nome: "Torrada tradicional “Pita Toast”", quantidade: "30 unidades", peso: "30 g", calorias: 111 },
        
          
            { nome: "Brie Luna", quantidade: "1 fatia", peso: "30 g", calorias: 104 },
            { nome: "Brie “Polenghi”", quantidade: "2 fatias", peso: "30 g", calorias: 100 },
            { nome: "Camembert Luna", quantidade: "1 unidade", peso: "50 g", calorias: 173 },
            { nome: "Camembert “President”", quantidade: "1 fatia", peso: "30 g", calorias: 84 },
            { nome: "Catupiry", quantidade: "1 col. sopa", peso: "30 g", calorias: 68 },
            { nome: "Chancliche com zattar", quantidade: "1 col. sopa", peso: "20 g", calorias: 47 },
            { nome: "Cheddar", quantidade: "1 fatia", peso: "30 g", calorias: 120 },
            { nome: "Cottage “Tirolez”", quantidade: "2 col. sopa", peso: "50 g", calorias: 47 },
            { nome: "Cream Cheese “Danúbio”", quantidade: "3 col. sopa", peso: "30 g", calorias: 75 },
            { nome: "Cream Cheese light “Danúbio”", quantidade: "3 col. sopa", peso: "30 g", calorias: 61 },
            { nome: "Cream Cheese Philadelphia light", quantidade: "1 col. sopa", peso: "20 g", calorias: 14 },
            { nome: "Cream Cheese Philadelphia", quantidade: "1 col. sopa", peso: "20 g", calorias: 20 },
            { nome: "Ementhal suíço", quantidade: "1 fatia", peso: "30 g", calorias: 119 },
            { nome: "Ementhal “Polenghi”", quantidade: "1 fatia", peso: "30 g", calorias: 115 },
            { nome: "Estepe", quantidade: "1 fatia", peso: "30 g", calorias: 100 },
            { nome: "Fondue Luna", quantidade: "1 porção", peso: "67 g", calorias: 276 },
            { nome: "Fondue de queijo “La Table D’or”", quantidade: "2 col. sopa", peso: "30 g", calorias: 76 },
            { nome: "Fundido", quantidade: "1 fatia", peso: "35 g", calorias: 124 },
            { nome: "Gorgonzola", quantidade: "1 fatia média", peso: "38 g", calorias: 182 },
            { nome: "Gouda Luna", quantidade: "1 fatia", peso: "30 g", calorias: 107 },
            { nome: "Gouda “Polenghi”", quantidade: "1 fatia", peso: "30 g", calorias: 105 },
            { nome: "Gruyère Luna", quantidade: "1 porção", peso: "25 g", calorias: 89 },
            { nome: "Gruyère “Polenghi”", quantidade: "1 fatia", peso: "30 g", calorias: 115 },
            { nome: "Holanda", quantidade: "1 fatia", peso: "30 g", calorias: 103 },
            { nome: "Itálico Luna", quantidade: "1 fatia", peso: "30 g", calorias: 107 },
            { nome: "Liederkranz", quantidade: "1 fatia", peso: "30 g", calorias: 90 },
            { nome: "Limburguês suíço", quantidade: "1 fatia", peso: "30 g", calorias: 97 },
            { nome: "Luninho Luna", quantidade: "1 unidade", peso: "–", calorias: 53 },
            { nome: "Mussarela", quantidade: "1 fatia média", peso: "20 g", calorias: 65 },
            { nome: "Mussarela de búfala", quantidade: "1 unidade", peso: "30 g", calorias: 95 },
            { nome: "Neufchatel suíço", quantidade: "1 fatia", peso: "30 g", calorias: 87 },
            { nome: "Palmira", quantidade: "1 fatia", peso: "30 g", calorias: 115 },
            { nome: "Parmesão", quantidade: "1 fatia", peso: "39 g", calorias: 168 },
            { nome: "Parmesão ralado", quantidade: "1 col. sopa", peso: "10 g", calorias: 47 },
            { nome: "Pecorino", quantidade: "1 fatia", peso: "35 g", calorias: 128 },
            { nome: "Petit Suisse", quantidade: "1 unidade", peso: "25 g", calorias: 45 },
            { nome: "Polenguinho", quantidade: "1 unidade", peso: "20 g", calorias: 62 },
            { nome: "Polenguinho light", quantidade: "1 unidade", peso: "20 g", calorias: 52 },
            { nome: "Prato", quantidade: "1 fatia média", peso: "15 g", calorias: 59 },
            { nome: "Provolone", quantidade: "1 fatia média", peso: "15 g", calorias: 51 },
            { nome: "Quarticolo", quantidade: "1 porção", peso: "30 g", calorias: 78 },
            { nome: "Queijo coalho na brasa", quantidade: "1 espeto", peso: "60 g", calorias: 168 },
            { nome: "Queijo de cabra “Chamonix”", quantidade: "2 fatias", peso: "30 g", calorias: 80 },
            { nome: "Queijo-de-minas “Danubio”", quantidade: "1 fatia média", peso: "30 g", calorias: 67 },
            { nome: "Queijo-de-minas padrão “Quatá”", quantidade: "1 fatia", peso: "30 g", calorias: 114 },
            { nome: "Queijo-do-norte", quantidade: "1 fatia", peso: "30 g", calorias: 115 },
            { nome: "Queijo-do-reino suíço", quantidade: "1 fatia", peso: "30 g", calorias: 115 },
            { nome: "Requeijão", quantidade: "1 col. sopa", peso: "30 g", calorias: 74 },
            { nome: "Requeijão light", quantidade: "1 col. sopa", peso: "30 g", calorias: 41 },
            { nome: "Roqueford", quantidade: "1 porção", peso: "25 g", calorias: 100 },
            { nome: "Ricota “Tirolez”", quantidade: "1 fatia", peso: "30 g", calorias: 52 },
            { nome: "Saint Paulin Luna", quantidade: "1 fatia", peso: "30 g", calorias: 101 },
            { nome: "Suíço", quantidade: "1 fatia", peso: "30 g", calorias: 122 },
            { nome: "Tilsit Luna", quantidade: "1 fatia", peso: "35 g", calorias: 132 },
            { nome: "Tofu (queijo de soja)", quantidade: "1 fatia média", peso: "28 g", calorias: 41 },
            
              { nome: "Bebida Láctea com Polpa de Morango Dan Up “Danone”", quantidade: "1 pote", peso: "180 g", calorias: 157 },
              { nome: "Chandelle de Chocolate ao Leite “Nestlé”", quantidade: "1 pote", peso: "110 g", calorias: 152 },
              { nome: "Chandelle Sensação de Chocolate com Calda de Morango “Nestlé”", quantidade: "1 pote", peso: "110 g", calorias: 166 },
              { nome: "Coalhada Parcialmente Desnatada “Vigor”", quantidade: "1 pote", peso: "200 ml", calorias: 124 },
              { nome: "Coalhada Seca Natural “Alibey”", quantidade: "1 col. sopa", peso: "30 g", calorias: 37 },
              { nome: "Flan de Baunilha com Calda de Caramelo Moça “Nestlé”", quantidade: "1 pote", peso: "110 g", calorias: 128 },
              { nome: "Frozen yogurt Yogen Früz", quantidade: "", peso: "100 g", calorias: 88 },
              { nome: "Frozen yogurt Yogolove", quantidade: "", peso: "100 g", calorias: 111 },
              { nome: "Frozen yogurt Yoggi", quantidade: "", peso: "100 g", calorias: 88 },
              { nome: "Frozen yogurt Yogoberry", quantidade: "", peso: "100 g", calorias: 88 },
              { nome: "Frozen yogurt Yoforia", quantidade: "", peso: "100 g", calorias: 90 },
              { nome: "Frozen yogurt Tutti Frutti", quantidade: "", peso: "100 g", calorias: 107 },
              { nome: "Frozen yogurt Bendita Fruta", quantidade: "", peso: "100 g", calorias: 85 },
              { nome: "Frozen yogurt Yogofresh", quantidade: "", peso: "100 g", calorias: 86 },
              { nome: "Iogurte Activia Morango Mix com Corn – Flakes “Danone”", quantidade: "1 pote", peso: "110 g", calorias: 144 },
              { nome: "Iogurte com Aveia e Fibras Activia “Danone”", quantidade: "1 pote", peso: "100 g", calorias: 100 },
              { nome: "Iogurte com Coco Ralado “Batavo”", quantidade: "1 pote", peso: "200 g", calorias: 217 },
              { nome: "Iogurte com Mel Sabor Baunilha Activia “Danone”", quantidade: "1 pote", peso: "100 g", calorias: 106 },
              { nome: "Iogurte com Pedaços de Morango “Batavo”", quantidade: "1 pote", peso: "200 g", calorias: 196 },
              { nome: "Iogurte com Polpa de Ameixa Activia “Danone”", quantidade: "1 pote", peso: "100 g", calorias: 110 },
              { nome: "Iogurte com Polpa de Cereja Activia “Danone”", quantidade: "1 pote", peso: "100 g", calorias: 106 },
              { nome: "Iogurte com Polpa de Coco “Ati Latte”", quantidade: "1 pote", peso: "180 g", calorias: 173 },
              { nome: "Iogurte com Polpa de Mamão, Banana e Maça “Vigor”", quantidade: "1 pote", peso: "200 g", calorias: 153 },
              { nome: "Iogurte com polpa de morango “Danone”", quantidade: "1 pote", peso: "100 g", calorias: 90 },
              { nome: "Iogurte com Polpa e Geléia de Morango Activia “Danone”", quantidade: "1 pote", peso: "120 g", calorias: 145 },
              { nome: "Iogurte Desnatado com Polpa de Ameixa e Fibras Bio Fibras “Batavo”", quantidade: "1 pote", peso: "110 g", calorias: 89 },
              { nome: "Iogurte Integral “Paulista”", quantidade: "1 pote", peso: "170 g", calorias: 109 },
              { nome: "Iogurte Integral com Laranja, Cenoura e Mel Activia “Danone”", quantidade: "1 pote", peso: "170 g", calorias: 160 },
              { nome: "Iogurte Integral com Mel “Vigor”", quantidade: "1 pote", peso: "200 g", calorias: 221 },
              { nome: "Iogurte Integral com Polpa de Ameixa “Vigor”", quantidade: "1 pote", peso: "200 g", calorias: 235 },
              { nome: "Iogurte Integral com Polpa de Morango e Fibra Nesvita “Nestlé”", quantidade: "1 pote", peso: "100 g", calorias: 91 },
              { nome: "Iogurte Integral com Suco de Uva e Sabor Sálvia “Nestlé”", quantidade: "1 pote", peso: "200 g", calorias: 186 },
              { nome: "Iogurte Integral Natural Activia “Danone”", quantidade: "1 pote", peso: "170 g", calorias: 132 },
              { nome: "Iogurte light com adoçante “Leco”", quantidade: "1 copo", peso: "200 ml", calorias: 66 },
              { nome: "Iogurte Light com Pedaço de Frutas Amarelas Pense Light “Batavo”", quantidade: "1 pote", peso: "110 g", calorias: 45 },
              { nome: "Iogurte light com pedaços de pêssego e proteína de soja “Leco”", quantidade: "1 pote", peso: "115 g", calorias: 60 },
              { nome: "Iogurte Light com Polpa de Mamão “Batavo”", quantidade: "1 pote", peso: "170 g", calorias: 45 },
              { nome: "Iogurte Light Desnatado com Polpa de Morango Molico “Nestlé”", quantidade: "1 copo", peso: "200 ml", calorias: 62 },
              { nome: "Iogurte Light Morango com Chocolate Molico Tentação “Nestlé”", quantidade: "1 pote", peso: "100 g", calorias: 53 },
              { nome: "Iogurte Natural Desnatado “Nestlé”", quantidade: "1 pote", peso: "185 g", calorias: 79 },
              { nome: "Iogurte Parcialmente Desnatado com Aveia Activia “Danone”", quantidade: "1 pote", peso: "180 g", calorias: 144 },
              { nome: "Iogurte Semi Desnatado com Cereal e Polpa de Morango “Ninho Solei”", quantidade: "1 copo", peso: "200 ml", calorias: 171 },
              { nome: "Iogurte Semi Desnatado com Polpa de Frutas Vermelhas Bliss “Nestlé”", quantidade: "1 pote", peso: "180 g", calorias: 158 },
              { nome: "Iogurte Semi Desnatado com Suco de Maracujá, Laranja e Acerola Kissy “Batavo”", quantidade: "1 pote", peso: "180 g", calorias: 102 },
              { nome: "Petit Suisse com Polpa de Morango Danoninho “Danone”", quantidade: "1 pote", peso: "45 g", calorias: 54 },
              { nome: "Petit Suisse de Chocolate Vigorzinho “Vigor”", quantidade: "1 pote", peso: "45 g", calorias: 83 },
              { nome: "Sobremesa Láctea Sabor Beijinho “Paulista”", quantidade: "1 pote", peso: "100 g", calorias: 143 },
              

                { nome: "Azeite de dendê", quantidade: "1 col. sopa", peso: "8 ml", calorias: 72 },
                { nome: "Azeite de oliva", quantidade: "1 col. sopa", peso: "13 ml", calorias: 117 },
                { nome: "Creme de leite", quantidade: "1 col. sopa", peso: "15 g", calorias: 38 },
                { nome: "Creme de leite light", quantidade: "1 col. sopa", peso: "15 g", calorias: 24 },
                { nome: "Gordura vegetal hidrogenada", quantidade: "1 col. sopa", peso: "21 g", calorias: 189 },
                { nome: "Manteiga", quantidade: "1 col. sopa", peso: "10 g", calorias: 75 },
                { nome: "Manteiga e margarina “Amélia”", quantidade: "1 col. sopa", peso: "10 g", calorias: 72 },
                { nome: "Manteiga light", quantidade: "1 col. sopa", peso: "10 g", calorias: 43 },
                { nome: "Margarina", quantidade: "1 col. sopa", peso: "10 g", calorias: 70 },
                { nome: "Margarina light", quantidade: "1 col. sopa", peso: "10 g", calorias: 44 },
                { nome: "Óleo vegetal", quantidade: "1 col. sopa", peso: "12 ml", calorias: 108 },
  
  { nome: "Caldo de galinha em tablete “Knorr”", quantidade: "1 unidade", peso: "9,5 g", calorias: 20 },
  { nome: "Chester assado", quantidade: "1 fatia fina", peso: "20 g", calorias: 41 },
  { nome: "Coxa de frango assada com pele", quantidade: "1 unidade", peso: "46 g", calorias: 99 },
  { nome: "Coxa de frango cozida sem pele", quantidade: "1 unidade", peso: "46 g", calorias: 77 },
  { nome: "Espetinho de coração de frango na brasa", quantidade: "1 unidade", peso: "50 g", calorias: 104 },
  { nome: "Espetinho de frango na brasa", quantidade: "1 unidade", peso: "50 g", calorias: 80 },
  { nome: "Fígado de galinha cozido", quantidade: "1 col. sopa", peso: "25 g", calorias: 35 },
  { nome: "Filé de frango à milanesa", quantidade: "1 filé médio", peso: "140 g", calorias: 435 },
  { nome: "Filé de frango à parmegiana “Sadia”", quantidade: "1 filé médio", peso: "275 g", calorias: 335 },
  { nome: "Filé de frango grelhado", quantidade: "1 unidade média", peso: "125 g", calorias: 199 },
  { nome: "Frango ensopado", quantidade: "1 peito médio", peso: "180 g", calorias: 229 },
  { nome: "Hamburguer de frango (grelhado)", quantidade: "1 unidade", peso: "85 g", calorias: 164 },
  { nome: "Hamburguer de peru (grelhado)", quantidade: "1 e 1/2 unidade", peso: "80 g", calorias: 166 },
  { nome: "Miúdos de galinha", quantidade: "1 moela média", peso: "18 g", calorias: 29 },
  { nome: "Nuggets de frango", quantidade: "5 unidades", peso: "130 g", calorias: 326 },
  { nome: "Peru assado", quantidade: "1 fatia média", peso: "32 g", calorias: 52 },
  { nome: "Sobrecoxa de frango assada com pele", quantidade: "1 unidade", peso: "65 g", calorias: 169 },
  { nome: "Sobrecoxa de frango assada sem pele", quantidade: "1 unidade", peso: "65 g", calorias: 151 },
     
  { nome: "Almôndega caseira frita", quantidade: "1 unidade média", peso: "50 g", calorias: 102 },
  { nome: "Bife à milanesa", quantidade: "1 unidade média", peso: "80 g", calorias: 230 },
  { nome: "Bife à parmegiana", quantidade: "1 unidade média", peso: "150 g", calorias: 491 },
  { nome: "Bife de fígado", quantidade: "1 unidade grande", peso: "130 g", calorias: 293 },
  { nome: "Bife grelhado (contra-filé com gordura)", quantidade: "1 unidade média", peso: "100 g", calorias: 278 },
  { nome: "Bife grelhado (contra-filé sem gordura)", quantidade: "1 unidade média", peso: "90 g", calorias: 200 },
  { nome: "Bife grelhado (filé mignon sem gordura)", quantidade: "1 unidade média", peso: "90 g", calorias: 198 },
  { nome: "Bife grelhado (miolo de alcatra sem gordura)", quantidade: "1 unidade média", peso: "90 g", calorias: 217 },
  { nome: "Bife rolê", quantidade: "1 unidade média", peso: "100 g", calorias: 179 },
  { nome: "Caldo de carne em tablete “Knorr”", quantidade: "1 unidade", peso: "9.5 g", calorias: 25 },
  { nome: "Carne assada", quantidade: "1 fatia média", peso: "90 g", calorias: 259 },
  { nome: "Carne cozida (lagarto)", quantidade: "1 fatia média", peso: "75 g", calorias: 134 },
  { nome: "Carne cozida (músculo)", quantidade: "1 fatia média", peso: "75 g", calorias: 146 },
  { nome: "Carne moída refogada (acém)", quantidade: "1 col. sopa", peso: "30 g", calorias: 64 },
  { nome: "Carne seca cozida", quantidade: "1 pedaço médio", peso: "65 g", calorias: 205 },
  { nome: "Carpaccio", quantidade: "10 fatias", peso: "80 g", calorias: 120 },
  { nome: "Costela de boi assado", quantidade: "1 pedaço médio", peso: "40 g", calorias: 181 },
  { nome: "Espetinho de carne na brasa", quantidade: "1 unidade", peso: "50 g", calorias: 119 },
  { nome: "Hambúrguer (frito)", quantidade: "1 unidade", peso: "85 g", calorias: 219 },
  { nome: "Hambúrguer (grelhado)", quantidade: "1 unidade", peso: "85 g", calorias: 178 },
  { nome: "Picanha na brasa (sem gordura)", quantidade: "1 pedaço médio", peso: "100 g", calorias: 238 },
  { nome: "Quibe assado", quantidade: "1 pedaço grande", peso: "80 g", calorias: 145 },

  { nome: "Bacon frito", quantidade: "1 fatia média", peso: "15 g", calorias: 99 },
  { nome: "Bisteca de porco (na brasa)", quantidade: "1 unidade", peso: "100 g", calorias: 280 },
  { nome: "Costela de porco (assada)", quantidade: "1 unidade", peso: "115 g", calorias: 462 },
  { nome: "Leitão assado", quantidade: "1 pedaço médio", peso: "85 g", calorias: 190 },
  { nome: "Lombo assado", quantidade: "1 fatia", peso: "100 g", calorias: 125 },
  { nome: "Paio", quantidade: "1 unidade", peso: "160 g", calorias: 363 },
  { nome: "Pernil assado", quantidade: "1 fatia", peso: "100 g", calorias: 158 },
  { nome: "Rabo de porco (cozido)", quantidade: "3 unidades", peso: "100 g", calorias: 377 },
  { nome: "Tender assado", quantidade: "1 fatia", peso: "100 g", calorias: 121 },
  { nome: "Toucinho (frito)", quantidade: "1 fatia", peso: "15 g", calorias: 105 },
          
  { nome: "Apresuntado “Perdigão”", quantidade: "1 fatia", peso: "30 g", calorias: 114 },
  { nome: "Chester “Perdigão”", quantidade: "2 fatias", peso: "30 g", calorias: 36 },
  { nome: "Copa “Sadia”", quantidade: "10 fatias", peso: "40 g", calorias: 137 },
  { nome: "Linguiça de frango (na brasa)", quantidade: "1 unidade média", peso: "60 g", calorias: 146 },
  { nome: "Linguiça de porco (na brasa)", quantidade: "1 unidade média", peso: "60 g", calorias: 177 },
  { nome: "Lombinho “Ceratti”", quantidade: "2 fatias", peso: "50 g", calorias: 78 },
  { nome: "Mortadela “Ceratti”", quantidade: "3 fatias", peso: "50 g", calorias: 120 },
  { nome: "Peito de peru “Perdigão”", quantidade: "2 fatias", peso: "30 g", calorias: 33 },
  { nome: "Presunto cozido com capa de gordura “Sadia”", quantidade: "2 fatias", peso: "40 g", calorias: 62 },
  { nome: "Presunto cozido sem capa de gordura “Perdigão”", quantidade: "2 fatias", peso: "40 g", calorias: 48 },
  { nome: "Presunto parma “Sadia”", quantidade: "2 fatias", peso: "40 g", calorias: 84 },
  { nome: "Salame “Sadia”", quantidade: "7 fatias", peso: "40 g", calorias: 148 },
  { nome: "Salsicha", quantidade: "1 unidade", peso: "50 g", calorias: 146 },
  { nome: "Salsicha de frango", quantidade: "1 unidade", peso: "50 g", calorias: 120 },
  { nome: "Salsicha de chester", quantidade: "1 unidade", peso: "50 g", calorias: 90 },

  { nome: "Camarão médio cozido", quantidade: "10 unidades", peso: "100 g", calorias: 90 },
  { nome: "Camarão pequeno frito", quantidade: "1 col. sopa", peso: "20 g", calorias: 62 },
  { nome: "Camarão cozido pequeno", quantidade: "5 col. sopa", peso: "100 g", calorias: 82 },
  { nome: "Camarão frito grande", quantidade: "5 unidades", peso: "100 g", calorias: 310 },
  { nome: "Camarão cozido grande", quantidade: "5 unidades", peso: "100 g", calorias: 82 },
  { nome: "Camarão seco descascado do norte", quantidade: "5 médios", peso: "100 g", calorias: 158 },
  { nome: "Casquinha de caranguejo", quantidade: "1 unidade", peso: "", calorias: 250 },
  { nome: "Casquinha de siri", quantidade: "1 unidade", peso: "100 g", calorias: 413 },
  { nome: "Kani-kama", quantidade: "1 unidade", peso: "16 g", calorias: 13 },
  { nome: "Lagostim", quantidade: "8 unidades", peso: "100 g", calorias: 112 },
  { nome: "Lagosta grelhada c/ manteiga 308", quantidade: "1 unidade", peso: "200 g", calorias: 308 },
  { nome: "Lagosta cozida", quantidade: "1 unidade", peso: "200 g", calorias: 196 },
  { nome: "Lula à dorê", quantidade: "1 pires de chá", peso: "100 g", calorias: 190 },
  { nome: "Lula cozida", quantidade: "1 pires de chá", peso: "100 g", calorias: 92 },
  { nome: "Marisco", quantidade: "1 xíc. chá", peso: "100 g", calorias: 186 },
  { nome: "Ostra crua", quantidade: "3 unidades", peso: "100 g", calorias: 81 },
  { nome: "Ovas de peixe cruas", quantidade: "1/2 xíc. chá", peso: "100 g", calorias: 123 },
  { nome: "Polvo refogado", quantidade: "1 escumadeira", peso: "60 g", calorias: 49 },

  { nome: "Gemada", quantidade: "1 porção", peso: "150 ml", calorias: 210 },
  { nome: "Omelete com queijo mussarela", quantidade: "1 porção", peso: "100 g", calorias: 220 },
  { nome: "Omelete simples", quantidade: "1 unidade", peso: "65 g", calorias: 110 },
  { nome: "Ovo cozido", quantidade: "1 unidade", peso: "45 g", calorias: 71 },
  { nome: "Ovo de codorna", quantidade: "1 unidade", peso: "10 g", calorias: 16 },
  { nome: "Ovo frito", quantidade: "1 unidade", peso: "50 g", calorias: 105 },
  { nome: "Ovo mexido simples", quantidade: "1 unidade", peso: "60 g", calorias: 120 },

  { nome: "Arraia", quantidade: "1 posta", peso: "100g", calorias: 90 },
  { nome: "Arenque", quantidade: "2 filés", peso: "100g", calorias: 230 },
  { nome: "Anchova cozida", quantidade: "1 filé", peso: "100g", calorias: 118 },
  { nome: "Anchova à milanesa", quantidade: "1 filé", peso: "100g", calorias: 210 },
  { nome: "Cavala", quantidade: "2 unidades", peso: "100 g", calorias: 260 },
  { nome: "Agulha frito", quantidade: "5 unidades", peso: "100 g", calorias: 94 },
  { nome: "Agulha cru", quantidade: "5 unidades", peso: "100g", calorias: 28 },
  { nome: "Atum cru", quantidade: "1 posta", peso: "100 g", calorias: 118 },
  { nome: "Atum em conserva (água)", quantidade: "1 col. sopa", peso: "45 g", calorias: 52 },
  { nome: "Atum em conserva (óleo)", quantidade: "1 col. sopa", peso: "45 g", calorias: 85 },
  { nome: "Bacalhau assado", quantidade: "1 posta", peso: "100 g", calorias: 110 },
  { nome: "Bacalhau cozido", quantidade: "1 posta", peso: "100g", calorias: 100 },
  { nome: "Baiacu", quantidade: "1 filé", peso: "100g", calorias: 92 },
  { nome: "Badejo cozido", quantidade: "2 filés", peso: "100g", calorias: 131 },
  { nome: "Badejo cru", quantidade: "2 filés", peso: "100 g", calorias: 97 },
  { nome: "Bagre cozido", quantidade: "1 posta", peso: "100g", calorias: 120 },
  { nome: "Beijupirá", quantidade: "1 posta", peso: "100 g", calorias: 131 },
  { nome: "Bonito em conserva", quantidade: "1 col. sopa", peso: "20g", calorias: 34 },
  { nome: "Bonito cru", quantidade: "1 posta", peso: "100 g", calorias: 149 },
  { nome: "Cação cru", quantidade: "1 posta", peso: "100 g", calorias: 129 },
  { nome: "Caviar vermelho de carpa", quantidade: "1 porção", peso: "100 g", calorias: 130 },
  { nome: "Caviar", quantidade: "1 xíc. chá", peso: "10 g", calorias: 29 },
  { nome: "Dourado", quantidade: "1 posta", peso: "100 g", calorias: 80 },
  { nome: "Esturjão", quantidade: "1 porção", peso: "100 g", calorias: 90 },
  { nome: "Esturjão defumado", quantidade: "1 porção", peso: "100 g", calorias: 141 },
  { nome: "Espada grelhado", quantidade: "1 porção", peso: "100 g", calorias: 158 },
  { nome: "Galo", quantidade: "1 porção", peso: "100 g", calorias: 109 },
  { nome: "Garoupa São Tomé", quantidade: "1 posta", peso: "100 g", calorias: 89 },
  { nome: "Gordinho", quantidade: "1 porção", peso: "100 g", calorias: 103 },
  { nome: "Haddock cozido", quantidade: "1 filé", peso: "100 g", calorias: 100 },
  { nome: "Haddock defumado", quantidade: "1 filé", peso: "100 g", calorias: 78 },
  { nome: "Manjuba frita", quantidade: "10 unidades", peso: "100 g", calorias: 285 },
  { nome: "Mero vermelho", quantidade: "1 porção", peso: "100 g", calorias: 96 },
  { nome: "Merluza crua", quantidade: "1 filé", peso: "100 g", calorias: 200 },
  { nome: "Merluza cozida", quantidade: "1 filé", peso: "100 g", calorias: 232 },
  { nome: "Moréia", quantidade: "1 porção", peso: "100 g", calorias: 126 },
  { nome: "Namorado cozido", quantidade: "1 filé", peso: "100 g", calorias: 122 },
  { nome: "Namorado cru", quantidade: "1 filé", peso: "100 g", calorias: 87 },
  { nome: "Namorado à milanesa", quantidade: "1 filé", peso: "100 g", calorias: 190 },
  { nome: "Ovas de peixe em conserva", quantidade: "1/2 xíc. chá", peso: "100 g", calorias: 383 },
  { nome: "Ovas de peixe cruas", quantidade: "1/12 xíc. chá", peso: "100 g", calorias: 123 },
  { nome: "Pescada frito", quantidade: "1 filé", peso: "100 g", calorias: 154 },
  { nome: "Pescada", quantidade: "1 filé", peso: "100 g", calorias: 97 },
  { nome: "Pescada em conserva", quantidade: "1 filé", peso: "100 g", calorias: 144 },
  { nome: "Pirarucu salgado", quantidade: "1 posta", peso: "100 g", calorias: 251 },
  { nome: "Pollock assado ou grelhado", quantidade: "1 filé", peso: "100 g", calorias: 110 },
  { nome: "Robalo", quantidade: "1 posta", peso: "100 g", calorias: 72 },
  { nome: "Salmão cru", quantidade: "1 filé", peso: "100 g", calorias: 211 },
  { nome: "Salmão defumado", quantidade: "1 filé", peso: "100 g", calorias: 204 },
  { nome: "Salmão grelhado", quantidade: "1 filé", peso: "100 g", calorias: 220 },
  { nome: "Sardinha Coqueiro em óleo comestível", quantidade: "4 unidades", peso: "100 g", calorias: 174 },
  { nome: "Sardinha em conserva c/ azeite", quantidade: "3 unidades", peso: "100 g", calorias: 298 },
  { nome: "Sardinha em conserva c/ molho de tomate", quantidade: "3 unidades", peso: "100 g", calorias: 173 },
  { nome: "Sardinha em conserva", quantidade: "4 unidades", peso: "100 g", calorias: 158 },
  { nome: "Serra salgado", quantidade: "1 posta", peso: "100 g", calorias: 189 },
  { nome: "Surubim cru", quantidade: "1 posta", peso: "100 g", calorias: 107 },
  { nome: "Surubim salgado", quantidade: "1 posta", peso: "100 g", calorias: 251 },
  { nome: "Tainha em conserva", quantidade: "1 posta", peso: "100 g", calorias: 145 },
  { nome: "Tainha cozida", quantidade: "1 posta", peso: "100 g", calorias: 204 },
  { nome: "Truta assada ou grelhada", quantidade: "1 filé", peso: "100 g", calorias: 150 },
  { nome: "Tubarão", quantidade: "1 posta", peso: "100 g", calorias: 294 },
  { nome: "Vermelho assado ou grelhado", quantidade: "1 porção", peso: "100 g", calorias: 130 },
  { nome: "Viola", quantidade: "1 porção", peso: "100 g", calorias: 127 },

  { nome: "Abacate", quantidade: "1 col. sopa amassado", peso: "45 g", calorias: 80 },
  { nome: "Abacaxi", quantidade: "1 fatia média", peso: "75 g", calorias: 44 },
  { nome: "Açaí", quantidade: "1 xíc. chá", peso: "100 g", calorias: 110 },
  { nome: "Acerola", quantidade: "1 unidade", peso: "–", calorias: 3 },
  { nome: "Ameixa amarela", quantidade: "1 unidade", peso: "25 g", calorias: 23 },
  { nome: "Ameixa preta seca", quantidade: "1 unidade", peso: "5 g", calorias: 10 },
  { nome: "Ameixa vermelha", quantidade: "1 unidade média", peso: "16 g", calorias: 9 },
  { nome: "Amêndoas", quantidade: "10 unidades", peso: "100 g", calorias: 640 },
  { nome: "Amendoim", quantidade: "1 xíc. de chá", peso: "100 g", calorias: 576 },
  { nome: "Amora silvestre", quantidade: "1/2 copo", peso: "100 g", calorias: 61 },
  { nome: "Avelã", quantidade: "10 unidades", peso: "100 g", calorias: 633 },
  { nome: "Banana-da-terra", quantidade: "1/2 unidade", peso: "100 g", calorias: 105 },
  { nome: "Banana maçã", quantidade: "1 unidade média", peso: "80 g", calorias: 97 },
  { nome: "Banana nanica", quantidade: "1 unidade", peso: "110 g", calorias: 89 },
  { nome: "Banana-nanica à milanesa", quantidade: "1/2 unidade", peso: "100 g", calorias: 308 },
  { nome: "Banana-ouro", quantidade: "2 unidades", peso: "100 g", calorias: 159 },
  { nome: "Banana passa", quantidade: "1 unidade", peso: "10 g", calorias: 35 },
  { nome: "Banana prata", quantidade: "1 unidade", peso: "70 g", calorias: 74 },
  { nome: "Cajá-manga", quantidade: "1 unidade", peso: "100 g", calorias: 46 },
  { nome: "Caju", quantidade: "1 unidade", peso: "150 g", calorias: 54 },
  { nome: "Caqui chocolate", quantidade: "1 unidade", peso: "113 g", calorias: 72 },
  { nome: "Caqui japonês", quantidade: "1 unidade", peso: "100 g", calorias: 86 },
  { nome: "Carambola", quantidade: "1 unidade", peso: "128 g", calorias: 59 },
  { nome: "Castanha", quantidade: "5 unidades", peso: "50 g", calorias: 100 },
  { nome: "Castanha-do-pará", quantidade: "1 xíc. chá", peso: "100 g", calorias: 1049 },
  { nome: "Castanha de caju torrada", quantidade: "1 xíc. chá", peso: "150 g", calorias: 914 },
  { nome: "Castanha européia crua", quantidade: "1 xíc. chá", peso: "100 g", calorias: 287 },
  { nome: "Cereja", quantidade: "1 unidade", peso: "7 g", calorias: 11 },
  { nome: "Coco ralado fresco", quantidade: "1 col. sopa", peso: "20 g", calorias: 50 },
  { nome: "Cupuaçu", quantidade: "1 unidade", peso: "100 g", calorias: 72 },
  { nome: "Damasco seco", quantidade: "1 unidade", peso: "7 g", calorias: 9 },
  { nome: "Figo", quantidade: "1 unidade", peso: "60 g", calorias: 19 },
  { nome: "Figo seco", quantidade: "1 unidade", peso: "30 g", calorias: 60 },
  { nome: "Framboesa", quantidade: "1 col. sopa", peso: "20 g", calorias: 12 },
  { nome: "Frutas cristalizadas", quantidade: "1 e 1/2 xic. chá", peso: "30 g", calorias: 92 },
  { nome: "Fruta-pão", quantidade: "1 unidade", peso: "–", calorias: 96 },
  { nome: "Goiaba branca", quantidade: "1 unidade", peso: "170 g", calorias: 58 },
  { nome: "Goiaba vermelha", quantidade: "1 unidade", peso: "170 g", calorias: 46 },
  { nome: "Grapefruit", quantidade: "1 unidade", peso: "200 g", calorias: 94 },
  { nome: "Graviola", quantidade: "1 unidade", peso: "100 g", calorias: 60 },
  { nome: "Jabuticaba", quantidade: "10 unidades", peso: "40 g", calorias: 14 },
  { nome: "Jaca", quantidade: "1 gomo", peso: "10 g", calorias: 9 },
  { nome: "Jatobá", quantidade: "1 unidade", peso: "–", calorias: 115 },
  { nome: "Kiwi", quantidade: "1 unidade", peso: "77 g", calorias: 44 },
  { nome: "Laranja-da-baía", quantidade: "1 unidade", peso: "–", calorias: 42 },
  { nome: "Laranja lima", quantidade: "1 unidade", peso: "109 g", calorias: 38 },
  { nome: "Laranja pera", quantidade: "1 unidade", peso: "137 g", calorias: 42 },
  { nome: "Laranjinha-japonesa", quantidade: "5 unidades", peso: "100 g", calorias: 48 },
  { nome: "Lima-da-pérsia", quantidade: "1 unidade", peso: "100 g", calorias: 32 },
  { nome: "Limão", quantidade: "1 unidade", peso: "60 g", calorias: 19 },
  { nome: "Manga desidratada “Fruitwell”", quantidade: "1 pacote", peso: "40 g", calorias: 141 },
  { nome: "Maçã desidratada “Jasmine”", quantidade: "1 pacote", peso: "40 g", calorias: 128 },
  { nome: "Maçã fugi", quantidade: "1 unidade", peso: "130 g", calorias: 78 },
  { nome: "Mamão formosa", quantidade: "1 fatia", peso: "100 g", calorias: 45 },
  { nome: "Mamão papaia", quantidade: "1 unidade", peso: "283 g", calorias: 99 },
  { nome: "Manga", quantidade: "1 xíc. chá", peso: "240 g", calorias: 144 },
  { nome: "Maracujá", quantidade: "1 unidade", peso: "38 g", calorias: 25 },
  { nome: "Melancia", quantidade: "1 fatia", peso: "148 g", calorias: 33 },
  { nome: "Melão", quantidade: "1 fatia", peso: "115 g", calorias: 28 },
  { nome: "Morango", quantidade: "10 unidades", peso: "120 g", calorias: 36 },
  { nome: "Nectarina", quantidade: "1 unidade", peso: "100 g", calorias: 64 },
  { nome: "Nêspera", quantidade: "1 unidade", peso: "60 g", calorias: 26 },
  { nome: "Nozes", quantidade: "1 unidade", peso: "10 g", calorias: 71 },
  { nome: "Nozes pecan", quantidade: "1/2 xíc. chá", peso: "50 g", calorias: 200 },
  { nome: "Pera", quantidade: "1 unidade", peso: "133 g", calorias: 56 },
  { nome: "Pequi", quantidade: "1 unidade", peso: "50 g", calorias: 40 },
  { nome: "Pêssego", quantidade: "1 unidade", peso: "113 g", calorias: 46 },
  { nome: "Pinha (fruta do conde)", quantidade: "1 unidade", peso: "60 g", calorias: 53 },
  { nome: "Pitanga", quantidade: "10 unidades", peso: "100 g", calorias: 47 },
  { nome: "Romã", quantidade: "1 unidade", peso: "100 g", calorias: 62 },
  { nome: "Salada de frutas", quantidade: "1 taça", peso: "100 g", calorias: 99 },
  { nome: "Sementes de abóbora torradas", quantidade: "2 c. sopa", peso: "30 g", calorias: 130 },
  { nome: "Sementes de gergelim secas", quantidade: "1 col. sopa", peso: "10 g", calorias: 59 },
  { nome: "Tâmara seca", quantidade: "1 unidade", peso: "30 g", calorias: 76 },
  { nome: "Tamarindo (polpa)", quantidade: "1/2 xíc. chá", peso: "100 g", calorias: 232 },
  { nome: "Tangerina", quantidade: "1 unidade", peso: "100 g", calorias: 36 },
  { nome: "Tangerina morgote", quantidade: "1 unidade", peso: "100 g", calorias: 43 },
  { nome: "Umbu", quantidade: "1 unidade", peso: "200 g", calorias: 54 },
  { nome: "Uva", quantidade: "10 unidades", peso: "100 g", calorias: 69 },
  { nome: "Uva-passa", quantidade: "1 col. sopa", peso: "10 g", calorias: 32 },
  { nome: "Uva-passa preta", quantidade: "1 col. sopa", peso: "10 g", calorias: 32 },
  { nome: "Uva-passa branca", quantidade: "1 col. sopa", peso: "10 g", calorias: 32 },
  { nome: "Uva-passa preta", quantidade: "1 col. sopa", peso: "10 g", calorias: 32 },
  { nome: "Uva-passa sem semente", quantidade: "1 col. sopa", peso: "10 g", calorias: 32 },
  { nome: "Uva-passa turca", quantidade: "1 col. sopa", peso: "10 g", calorias: 32 },

  { nome: "Ervilha em conserva “Jurema”", quantidade: "1 xíc. chá", peso: "130 g", calorias: 109 },
  { nome: "Fava em conserva “Zenny”", quantidade: "1 xíc. chá", peso: "125 g", calorias: 130 },
  { nome: "Feijão branco cozido", quantidade: "1 concha peq.", peso: "65 g", calorias: 79 },
  { nome: "Feijão branco em conserva “Jurema”", quantidade: "1 xíc. chá", peso: "130 g", calorias: 105 },
  { nome: "Feijão carioca cozido", quantidade: "1 concha peq.", peso: "59 g", calorias: 41 },
  { nome: "Feijão mulatinho cozido", quantidade: "1 concha peq.", peso: "59 g", calorias: 73 },
  { nome: "Feijão preto cozido", quantidade: "1 concha peq.", peso: "59 g", calorias: 69 },
  { nome: "Grão de bico cozido", quantidade: "1 concha peq.", peso: "60 g", calorias: 82 },
  { nome: "Grão-de-bico em conserva “Casino”", quantidade: "1 xíc. chá", peso: "130 g", calorias: 154 },
  { nome: "Lentilha cozida", quantidade: "1 concha peq.", peso: "60 g", calorias: 65 },
  { nome: "Tremoço", quantidade: "1 xíc. chá", peso: "65 g", calorias: 50 },

  { nome: "Abóbora cozida", quantidade: "4 col. sopa", peso: "100 g", calorias: 40 },
  { nome: "Abóbora moranga cozida", quantidade: "1 pedaço médio", peso: "20 g", calorias: 10 },
  { nome: "Abobrinha cozida", quantidade: "1 xíc. chá picada", peso: "166 g", calorias: 18 },
  { nome: "Acelga cozida", quantidade: "1 xíc. chá", peso: "206 g", calorias: 23 },
  { nome: "Agrião", quantidade: "1 xíc. chá", peso: "42 g", calorias: 10 },
  { nome: "Alcachofra em conserva", quantidade: "1/4 xíc. chá picado", peso: "50 g", calorias: 8 },
  { nome: "Alface", quantidade: "1 folha", peso: "8 g", calorias: 1 },
  { nome: "Alfafa", quantidade: "1 xíc. de chá", peso: "50 g", calorias: 38 },
  { nome: "Alho-poró", quantidade: "1 xíc. de chá", peso: "100 g", calorias: 30 },
  { nome: "Almeirão (50g)", quantidade: "1 pires de chá", peso: "50 g", calorias: 14 },
  { nome: "Aspargo em conserva", quantidade: "1 unidade", peso: "10 g", calorias: 1 },
  { nome: "Azeitona", quantidade: "1 unidade", peso: "3 g", calorias: 4 },
  { nome: "Batata doce cozida", quantidade: "1 xíc. chá picada", peso: "200 g", calorias: 230 },
  { nome: "Batata cozida", quantidade: "1 unidade", peso: "140 g", calorias: 71 },
  { nome: "Batata frita", quantidade: "1 escumadeira", peso: "100 g", calorias: 267 },
  { nome: "Berinjela cozida", quantidade: "1 xíc. chá picada", peso: "206 g", calorias: 43 },
  { nome: "Berinjela italiana", quantidade: "4 col. sopa", peso: "40 g", calorias: 209 },
  { nome: "Bardana", quantidade: "1 pires de chá", peso: "100 g", calorias: 90 },
  { nome: "Beterraba cozida", quantidade: "1 unidade média", peso: "125 g", calorias: 55 },
  { nome: "Beterraba crua", quantidade: "1 unidade média", peso: "140 g", calorias: 65 },
  { nome: "Brócolis cozido", quantidade: "1 xíc. chá picado", peso: "107 g", calorias: 26 },
  { nome: "Broto de bambu", quantidade: "1 xíc. chá", peso: "70 g", calorias: 17 },
  { nome: "Broto de feijão", quantidade: "1 xíc. chá", peso: "70 g", calorias: 44 },
  { nome: "Cará cozido", quantidade: "2 unidades", peso: "100 g", calorias: 120 },
  { nome: "Cebola cozida", quantidade: "1 unidade", peso: "100 g", calorias: 41 },
  { nome: "Cebolinha em conserva", quantidade: "1/2 xíc. chá", peso: "50 g", calorias: 18 },
  { nome: "Cenoura cozida", quantidade: "1 unidade média", peso: "100 g", calorias: 54 },
  { nome: "Cenoura crua", quantidade: "1 unidade média", peso: "120 g", calorias: 54 },
  { nome: "Chuchu cozido", quantidade: "1 xíc. chá picado", peso: "155 g", calorias: 29 },
  { nome: "Cogumelo em conserva", quantidade: "1 xíc. chá", peso: "107 g", calorias: 26 },
  { nome: "Couve manteiga refogada", quantidade: "1 prato fundo", peso: "88 g", calorias: 58 },
  { nome: "Couve-flor cozida", quantidade: "1 xíc. chá picada", peso: "136 g", calorias: 19 },
  { nome: "Espinafre refogado", quantidade: "1 xíc. chá picado", peso: "205 g", calorias: 29 },
  { nome: "Mandioca cozida", quantidade: "1 pedaço médio", peso: "50 g", calorias: 57 },
  { nome: "Mandioquinha cozida", quantidade: "1 unidade", peso: "115 g", calorias: 72 },
  { nome: "Nabo", quantidade: "1 xíc. chá picado", peso: "142 g", calorias: 14 },
  { nome: "Palmito em conserva", quantidade: "1/4 xíc. chá picado", peso: "50 g", calorias: 14 },
  { nome: "Pepino (relish)", quantidade: "1 1/2 col. sopa", peso: "15 g", calorias: 19 },
  { nome: "Pepino japonês", quantidade: "1 unidade", peso: "130 g", calorias: 16 },
  { nome: "Picles", quantidade: "1 col. sopa", peso: "15 g", calorias: 6 },
  { nome: "Pimentão amarelo", quantidade: "1 col. sopa picado", peso: "24 g", calorias: 6 },
  { nome: "Quiabo refogado", quantidade: "1 unidade", peso: "15 g", calorias: 2 },
  { nome: "Rabanete", quantidade: "1 unidade", peso: "30 g", calorias: 4 },
  { nome: "Repolho branco", quantidade: "1 xíc. chá picado", peso: "94 g", calorias: 13 },
  { nome: "Repolho roxo", quantidade: "1 xíc. chá", peso: "77 g", calorias: 5 },
  { nome: "Rúcula", quantidade: "1 prato fundo", peso: "50 g", calorias: 7 },
  { nome: "Seleta de legumes enlatada", quantidade: "1 xíc. chá", peso: "130 g", calorias: 78 },
  { nome: "Salada de maionese e batata", quantidade: "5 colheres de sopa", peso: "190 g", calorias: 290 },
  { nome: "Tomate", quantidade: "1 unidade", peso: "109 g", calorias: 16 },
  { nome: "Tomate seco", quantidade: "2 col. sopa", peso: "30 g", calorias: 101 },
  { nome: "Vagem", quantidade: "1 xíc. chá", peso: "140 g", calorias: 25 },


  { nome: "Água tônica 'Antartica'", quantidade: "1 lata", peso: "350 ml", calorias: 105 },
  { nome: "Água tônica diet 'Antartica'", quantidade: "1 lata", peso: "350 ml", calorias: 0 },
  { nome: "Água-de-coco 'Kerococo'", quantidade: "1 copo", peso: "200 ml", calorias: 45 },
  { nome: "Bebida à base de soja sabor abacaxi 'Sollys'", quantidade: "1 copo", peso: "200 ml", calorias: 78 },
  { nome: "Bebida à base de soja sabor maçã 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 71 },
  { nome: "Bebida à base de soja sabor maçã light 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 43 },
  { nome: "Bebida à base de soja sabor original 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 78 },
  { nome: "Bebida à base de soja sabor pera 'Shefa'", quantidade: "1 copo", peso: "200 ml", calorias: 90 },
  { nome: "Bebida energética 'Red Bull'", quantidade: "1 lata", peso: "250 ml", calorias: 110 },
  { nome: "Bebida energética 'Red Bull' sugar free", quantidade: "1 lata", peso: "250 ml", calorias: 10 },
  { nome: "Café com açúcar", quantidade: "1 xíc. café", peso: "50 ml", calorias: 26 },
  { nome: "Café com adoçante", quantidade: "1 xícara", peso: "50 ml", calorias: 2 },
  { nome: "Café com leite integral", quantidade: "1 xícara", peso: "100 ml", calorias: 45 },
  { nome: "Café com leite integral e açúcar", quantidade: "1 xícara", peso: "100 ml", calorias: 69 },
  { nome: "Café com leite desnatado", quantidade: "1 xícara", peso: "100 ml", calorias: 28 },
  { nome: "Café com leite desnatado e açúcar", quantidade: "1 xícara", peso: "100 ml", calorias: 52 },
  { nome: "Café sem açúcar", quantidade: "1 xíc. café", peso: "50 ml", calorias: 2 },
  { nome: "Café Mocha com leite integral e chantili do Starbucks", quantidade: "1 copo", peso: "300 ml", calorias: 360 },
  { nome: "Café Mocha com leite destanatado do Starbucks", quantidade: "1 copo", peso: "300 ml", calorias: 220 },
  { nome: "Cappuccino tradicional puro", quantidade: "1 xícara", peso: "100 ml", calorias: 65 },
  { nome: "Cappuccino tradicional com açúcar", quantidade: "1 xícara", peso: "100 ml", calorias: 89 },
  { nome: "Cappuccino com leite desnatado e adoçante", quantidade: "1 xícara", peso: "100 ml", calorias: 48 },
  { nome: "Cappuccino com canela pequeno do Fran’s Café", quantidade: "1 xícara", peso: "50 ml", calorias: 52 },
  { nome: "Cappuccino com canela grande do Fran’s Café", quantidade: "1 xícara", peso: "100 ml", calorias: 95 },
  { nome: "Cappuccino chocolate pequeno do Fran’s Café", quantidade: "1 xícara", peso: "50 ml", calorias: 129 },
  { nome: "Cappuccino chocolate grande do Fran’s Café", quantidade: "1 xícara", peso: "100 ml", calorias: 251 },
  { nome: "Café mocha pequeno do Fran’s Café", quantidade: "1 xícara", peso: "50 ml", calorias: 66 },
  { nome: "Chocolate quente submarino do Fran’s Café", quantidade: "1 xícara", peso: "100 ml", calorias: 305 },
  { nome: "Caldo de cana", quantidade: "1 copo", peso: "200 ml", calorias: 138 },
  { nome: "Chá branco 'Feel Good'", quantidade: "1 copo", peso: "200 ml", calorias: 0 },
  { nome: "Chá mate natural 'Matte Leão'", quantidade: "1 copo", peso: "200 ml", calorias: 74 },
  { nome: "Chá mate natural diet 'Matte Leão'", quantidade: "1 copo", peso: "200 ml", calorias: 5 },
  { nome: "Chá preto com limão 'Lipton'", quantidade: "1 lata", peso: "340 ml", calorias: 122 },
  { nome: "Chá preto com limão light 'Lipton'", quantidade: "1 lata", peso: "340 ml", calorias: 0 },
  { nome: "Chá preto sabor pêssego 'Nestea'", quantidade: "1 lata", peso: "340 ml", calorias: 118 },
  { nome: "Chá verde sabor laranja com gengibre 'Feel Good'", quantidade: "1 copo", peso: "200 ml", calorias: 0 },
  { nome: "Isotônico sabor açaí-guaraná 'Gatorade'", quantidade: "1 copo", peso: "200 ml", calorias: 48 },
  { nome: "Isotônico sabor tangerina 'Gatorade'", quantidade: "1 copo", peso: "200 ml", calorias: 48 },
  { nome: "Milk shake de café do Fran’s Café", quantidade: "1 copo", peso: "500 ml", calorias: 668 },
  { nome: "Milk shake de chocolate diet do Fran’s Café", quantidade: "1 copo", peso: "500 ml", calorias: 292 },
  { nome: "Franccino Mocha com chantili do Fran’s Café", quantidade: "1 copo", peso: "500 ml", calorias: 498 },
  { nome: "Franccino Mocha sem chantili do Fran’s Café", quantidade: "1 copo", peso: "500 ml", calorias: 246 },
  { nome: "Refresco em pó sabor manga 'Mid'", quantidade: "1 copo", peso: "200 ml", calorias: 26 },
  { nome: "Refresco em pó sabor uva 'Tang'", quantidade: "1 copo", peso: "200 ml", calorias: 26 },
  { nome: "Refresco em pós sabor morango silvestre 'Clight'", quantidade: "1 copo", peso: "200 ml", calorias: 6 },
  { nome: "Refrigerante 'Pepsi' Twist", quantidade: "1 copo", peso: "200 ml", calorias: 94 },
  { nome: "Refrigerante 'Pepsi' Twist light", quantidade: "1 copo", peso: "200 ml", calorias: 0 },
  { nome: "Refrigerante 'Sprite' zero", quantidade: "1 copo", peso: "200 ml", calorias: 0 },
  { nome: "Refrigerante Coca Cola", quantidade: "1 copo", peso: "200 ml", calorias: 85 },
  { nome: "Refrigerante Coca Cola light", quantidade: "1 copo", peso: "200 ml", calorias: 0 },
  { nome: "Refrigerante Coca Cola zero", quantidade: "1 copo", peso: "200 ml", calorias: 0 },
  { nome: "Refrigerante de limão 'H2O'", quantidade: "1 copo", peso: "200 ml", calorias: 0 },
  { nome: "Refrigerante guaraná 'Antartica'", quantidade: "1 copo", peso: "200 ml", calorias: 80 },
  { nome: "Refrigerante guaraná diet 'Antartica'", quantidade: "1 copo", peso: "200 ml", calorias: 0 },
  { nome: "Refrigerante sabor laranja 'Fanta'", quantidade: "1 copo", peso: "200 ml", calorias: 90 },
  { nome: "Refrigerante sabor laranja light 'Fanta'", quantidade: "1 copo", peso: "200 ml", calorias: 8 },
  { nome: "Refrigerante sabor uva 'Fanta'", quantidade: "1 copo", peso: "200 ml", calorias: 104 },
  { nome: "Refrigerante sabor uva light 'Fanta'", quantidade: "1 copo", peso: "200 ml", calorias: 12 },
  { nome: "Refrigerante soda limonada 'Antartica'", quantidade: "1 copo", peso: "200 ml", calorias: 92 },
  { nome: "Suco africano de lichia 'Ceres'", quantidade: "1 copo", peso: "200 ml", calorias: 105 },
  { nome: "Suco africano de uva vermelha 'Ceres'", quantidade: "1 copo", peso: "200 ml", calorias: 116 },
  { nome: "Suco concentrado sabor maracujá 'Maguary'", quantidade: "1 porção p/ misturar", peso: "22 ml", calorias: 13 },
  { nome: "Suco de abacaxi (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 92 },
  { nome: "Suco de acerola (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 56 },
  { nome: "Suco de acerola com laranja (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 66 },
  { nome: "Suco de acerola com melão (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 65 },
  { nome: "Suco de açaí (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 169 },
  { nome: "Suco de cajá (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 77 },
  { nome: "Suco de caju (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 92 },
  { nome: "Suco de goiaba (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 138 },
  { nome: "Suco de goiaba com leite (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 164 },
  { nome: "Suco de goiaba com pêssego (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 110 },
  { nome: "Suco de graviola (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 78 },
  { nome: "Suco de graviola com leite (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 94 },
  { nome: "Suco de laranja 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 104 },
  { nome: "Suco de laranja (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 96 },
  { nome: "Suco de lima 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 108 },
  { nome: "Suco de maçã 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 106 },
  { nome: "Suco de maracujá 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 68 },
  { nome: "Suco de melancia (caseiro) *", quantidade: "1 copo", peso: "200 ml", calorias: 50 },
  { nome: "Suco de morango 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 132 },
  { nome: "Suco de pêssego 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 102 },
  { nome: "Suco de uva integral", quantidade: "1 copo", peso: "200 ml", calorias: 154 },
  { nome: "Suco de uva light 'Ades'", quantidade: "1 copo", peso: "200 ml", calorias: 56 },
  { nome: "Suco de uva 'Del Valle'", quantidade: "1 copo", peso: "200 ml", calorias: 133 },
  { nome: "Suco de uva com abacaxi 'Del Valle'", quantidade: "1 copo", peso: "200 ml", calorias: 116 },
  { nome: "Suco de uva com maçã 'Del Valle'", quantidade: "1 copo", peso: "200 ml", calorias: 113 },
  { nome: "Suco de uva com pêssego 'Del Valle'", quantidade: "1 copo", peso: "200 ml", calorias: 112 },
  { nome: "Suco de uva com tangerina 'Del Valle'", quantidade: "1 copo", peso: "200 ml", calorias: 112 },
  { nome: "Suco de uva com açaí 'Del Valle'", quantidade: "1 copo", peso: "200 ml", calorias: 123 },
  { nome: "Vinho branco 'Chardonnay'", quantidade: "1 taça", peso: "100 ml", calorias: 85 },
  { nome: "Vinho branco 'Sauvignon Blanc'", quantidade: "1 taça", peso: "100 ml", calorias: 85 },
  { nome: "Vinho branco 'Riesling'", quantidade: "1 taça", peso: "100 ml", calorias: 85 },
  { nome: "Vinho tinto 'Cabernet Sauvignon'", quantidade: "1 taça", peso: "100 ml", calorias: 70 },
  { nome: "Vinho tinto 'Merlot'", quantidade: "1 taça", peso: "100 ml", calorias: 70 },
  { nome: "Vinho tinto 'Pinot Noir'", quantidade: "1 taça", peso: "100 ml", calorias: 70 },
  { nome: "Vinho espumante 'Champagne'", quantidade: "1 taça", peso: "100 ml", calorias: 85 },
  { nome: "Vinho espumante 'Prosecco'", quantidade: "1 taça", peso: "100 ml", calorias: 85 },

  { nome: "Cachaça", quantidade: "1 dose", peso: "50 ml", calorias: 115 },
  { nome: "Batida de frutas com leite condensado", quantidade: "1 copo", peso: "200 ml", calorias: 504 },
  { nome: "Caipirinha de limão com açúcar (aguardente)", quantidade: "1 copo", peso: "200 ml", calorias: 300 },
  { nome: "Caipirinha de limão com açúcar (vodca)", quantidade: "1 copo", peso: "200 ml", calorias: 310 },
  { nome: "Caipirinha de limão com adoçante (aguardente)", quantidade: "1 copo", peso: "200 ml", calorias: 240 },
  { nome: "Caipirinha de morango com açúcar (saquê)", quantidade: "1 copo", peso: "200 ml", calorias: 340 },
  { nome: "Cerveja", quantidade: "1 lata", peso: "350 ml", calorias: 151 },
  { nome: "Cerveja Malzbier 'Brahma'", quantidade: "1 long neck", peso: "355 ml", calorias: 199 },
  { nome: "Cerveja sem álcool", quantidade: "1 long neck", peso: "355 ml", calorias: 89 },
  { nome: "Champanhe", quantidade: "1 taça", peso: "125 ml", calorias: 110 },
  { nome: "Chope", quantidade: "1 tulipa", peso: "300 ml", calorias: 180 },
  { nome: "Conhaque", quantidade: "1 dose", peso: "50 ml", calorias: 125 },
  { nome: "Cuba Libre", quantidade: "1 copo", peso: "250 ml", calorias: 170 },
  { nome: "Gim", quantidade: "1 dose", peso: "30 ml", calorias: 60 },
  { nome: "Margarita", quantidade: "1 copo", peso: "150 ml", calorias: 131 },
  { nome: "Mojito", quantidade: "1 copo", peso: "200 ml", calorias: 250 },
  { nome: "Quentão", quantidade: "", peso: "100 ml", calorias: 294 },
  { nome: "Prosecco", quantidade: "1 taça", peso: "125 ml", calorias: 106 },
  { nome: "Rum", quantidade: "1 dose", peso: "50 ml", calorias: 110 },
  { nome: "Saquê", quantidade: "1 cálice", peso: "35 ml", calorias: 50 },
  { nome: "Smirnoff Ice", quantidade: "1 long neck", peso: "275 ml", calorias: 240 },
  { nome: "Tequila", quantidade: "1 dose", peso: "50 ml", calorias: 110 },
  { nome: "Uísque", quantidade: "1 dose", peso: "50 ml", calorias: 120 },
  { nome: "Vinho branco doce", quantidade: "1 taça", peso: "125 ml", calorias: 173 },
  { nome: "Vinho branco seco", quantidade: "1 taça", peso: "125 ml", calorias: 107 },
  { nome: "Vinho Quente", quantidade: "", peso: "100 ml", calorias: 120 },
  { nome: "Vinho tinto", quantidade: "1 taça", peso: "125 ml", calorias: 107 },
  { nome: "Vodca", quantidade: "1 dose", peso: "50 ml", calorias: 120 },
  
  { nome: "Achocolatado 'Nescau'", quantidade: "2 col. sopa", peso: "20 g", calorias: 75 },
  { nome: "Achocolatado 'Ovomaltine'", quantidade: "2 col. sopa", peso: "20 g", calorias: 74 },
  { nome: "Achocolatado light 'Nescau'", quantidade: "2 col. sopa", peso: "19 g", calorias: 64 },
  { nome: "Achocolatado diet 'Gold'", quantidade: "1 col. sopa", peso: "9 g", calorias: 35 },
  { nome: "Amendoim coberto de chocolate", quantidade: "", peso: "30 g", calorias: 160 },
  { nome: "Chocolate à base de soja 'Choc Soy'", quantidade: "1 unidade", peso: "25 g", calorias: 130 },
  { nome: "Chocolate Alpino 'Nestlé'", quantidade: "1 bombom", peso: "13 g", calorias: 68 },
  { nome: "Chocolate Alpino 'Nestlé'", quantidade: "1 barra", peso: "35 g", calorias: 185 },
  { nome: "Chocolate Alpino diet 'Nestlé'", quantidade: "1 barra", peso: "30 g", calorias: 143 },
  { nome: "Chocolate Amandita 'Lacta'", quantidade: "1 unidade", peso: "8 g", calorias: 43 },
  { nome: "Chocolate amargo 'Hershey’s'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 136 },
  { nome: "Chocolate amargo com amêndoas Talento 'Garoto'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 133 },
  { nome: "Chocolate amargo sabor menta 'Hershey’s'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 135 },
  { nome: "Chocolate ao leite 'Garoto'", quantidade: "1 barra", peso: "30 g", calorias: 156 },
  { nome: "Chocolate ao leite 'Hershey’s'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 132 },
  { nome: "Chocolate ao leite c/ amêndoas e passas Talento 'Garoto'", quantidade: "4 quadradinhos", peso: "30 g", calorias: 160 },
  { nome: "Chocolate ao leite c/ avelãs Talento 'Garoto'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 137 },
  { nome: "Chocolate ao leite c/ castanha-do-pará Talento 'Garoto'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 137 },
  { nome: "Chocolate ao leite Classic 'Nestlé'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 134 },
  { nome: "Chocolate ao leite com amendoim Shot 'Lacta'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 138 },
  { nome: "Chocolate ao leite com avelã 'Lacta'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 135 },
  { nome: "Chocolate ao leite com avelã Milka 'Lacta'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 162 },
  { nome: "Chocolate ao leite com castanha de cajú 'Nestlé'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 133 },
  { nome: "Chocolate ao leite com castanha e caramelo crocante 'Lacta'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 133 },
  { nome: "Chocolate ao leite com cookies de chocolate 'Hershey’s'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 128 },
  { nome: "Chocolate ao leite com crocante Wonka 'Nestlé'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 122 },
  { nome: "Chocolate ao leite com flocos 'Garoto'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 130 },
  { nome: "Chocolate ao leite com pedaços de biscoitos Passatempo 'Nestlé'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 128 },
  { nome: "Chocolate ao leite com pedaços de cacau 'Nestlé'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 134 },
  { nome: "Chocolate ao Leite com Recheio de Leite 'Kinder'", quantidade: "2 barras", peso: "25 g", calorias: 139 },
  { nome: "Chocolate ao leite diet 'Nestlé'", quantidade: "1 barra", peso: "30 g", calorias: 143 },
  { nome: "Chocolate ao leite e branco Duo 'Nestlé'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 134 },
  { nome: "Chocolate ao leite Lacta", quantidade: "4 quadradinhos", peso: "25 g", calorias: 133 },
  { nome: "Chocolate Baton 'Garoto'", quantidade: "1 unidade", peso: "16 g", calorias: 86 },
  { nome: "Chocolate Baton branco 'Garoto'", quantidade: "1 unidade", peso: "16 g", calorias: 89 },
  { nome: "Chocolate Bis 'Lacta'", quantidade: "1 unidade", peso: "7,5 g", calorias: 35 },
  { nome: "Chocolate Bis branco 'Lacta'", quantidade: "1 unidade", peso: "7,5 g", calorias: 35 },
  { nome: "Bombom 'Ferrero Rocher'", quantidade: "1 bombom", peso: "13 g", calorias: 73 },
  { nome: "Chocolate branco com cereais e uvas passas Talento 'Garoto'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 131 },
  { nome: "Chocolate branco com cookies 'Hershey’s'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 130 },
  { nome: "Chocolate Charge 'Nestlé'", quantidade: "1 unidade", peso: "40 g", calorias: 187 },
  { nome: "Chocolate granulado cacau Visconti", quantidade: "1 pacote", peso: "90 g", calorias: 325 },
  { nome: "Chocolate em pó Garoto", quantidade: "1 c. sopa", peso: "6 g", calorias: 18 },
  { nome: "Chocolate Chokito 'Nestlé'", quantidade: "1 unidade", peso: "32 g", calorias: 140 },
  { nome: "Chocolate Chokito Nestlé", quantidade: "1 unidade mini", peso: "14 g", calorias: 64 },
  { nome: "Chocolate Chomp 'Nestlé'", quantidade: "1 bombom", peso: "19 g", calorias: 99 },
  { nome: "Chocolate Chumbinho 'Kopenhagen'", quantidade: "2 col. sopa", peso: "25 g", calorias: 121 },
  { nome: "Chocolate com recheio de caramelo 'Twix'", quantidade: "2 barras", peso: "32 g", calorias: 150 },
  { nome: "Chocolate Crunch 'Nestlé'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 129 },
  { nome: "Chocolate Diamante Negro 'Lacta'", quantidade: "1 barra", peso: "30 g", calorias: 155 },
  { nome: "Chocolate Diplomata 'Nestlé'", quantidade: "1 unidade mini", peso: "10 g", calorias: 55 },
  { nome: "Chocolate Galak 'Nestlé'", quantidade: "1 barra", peso: "30 g", calorias: 170 },
  { nome: "Chocolate Kinder ovo", quantidade: "1 unidade", peso: "20 g", calorias: 110 },
  { nome: "Chocolate Laka", quantidade: "1 barra", peso: "30 g", calorias: 156 },
  { nome: "Chocolate Lancy 'Lacta'", quantidade: "1 unidade", peso: "30 g", calorias: 150 },
  { nome: "Chocolate Língua-de-gato 'Kopenhagen'", quantidade: "4 unidades", peso: "25 g", calorias: 144 },
  { nome: "Chocolate Língua-de-gato light 'Kopenhagen'", quantidade: "4 unidades", peso: "25 g", calorias: 108 },
  { nome: "Chocolate M&M amendoim", quantidade: "1 pacote", peso: "49 g", calorias: 242 },
  { nome: "Chocolate M&M ao leite", quantidade: "1 pacote", peso: "52 g", calorias: 242 },
  { nome: "Chocolate meio amargo 'Lacta'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 125 },
  { nome: "Chocolate meio amargo 'Nestlé'", quantidade: "4 quadradinhos", peso: "25 g", calorias: 126 },
  { nome: "Chocolate Milkybar 'Nestlé'", quantidade: "1 unidade mini", peso: "20 g", calorias: 93 },
  { nome: "Chocolate Milkybar 'Nestlé'", quantidade: "1 unidade", peso: "28 g", calorias: 134 },
  { nome: "Chocolate Nescau barra 'Nestlé'", quantidade: "1 unidade", peso: "40 g", calorias: 204 },
  { nome: "Chocolate Nutella", quantidade: "2 col. sopa", peso: "37 g", calorias: 200 },
  { nome: "Chocolate Ouro Branco 'Lacta'", quantidade: "1 barra", peso: "35 g", calorias: 165 },
  { nome: "Chocolate Prestígio 'Nestlé'", quantidade: "1 barra", peso: "25 g", calorias: 137 },
  { nome: "Chocolate Prestígio 'Nestlé'", quantidade: "1 unidade", peso: "25 g", calorias: 139 },
  { nome: "Chocolate Snickers", quantidade: "1 unidade", peso: "52 g", calorias: 273 },
  { nome: "Chocolate Sonho de Valsa 'Lacta'", quantidade: "1 unidade", peso: "20 g", calorias: 105 },
  { nome: "Chocolate Sonho de Valsa 'Lacta'", quantidade: "1 caixa", peso: "500 g", calorias: 2495 },
  { nome: "Chocolate Suflair 'Nestlé'", quantidade: "1 unidade", peso: "20 g", calorias: 107 },
  { nome: "Chocolate Talento 'Garoto'", quantidade: "1 barra", peso: "30 g", calorias: 165 },
  { nome: "Chocolate Talento diet 'Garoto'", quantidade: "1 barra", peso: "25 g", calorias: 132 },
  { nome: "Chocolate Toblerone", quantidade: "1 barra", peso: "35 g", calorias: 188 },
  { nome: "Chocolate Toblerone branco", quantidade: "1 barra", peso: "35 g", calorias: 192 },
  { nome: "Chocolate Twix", quantidade: "1 unidade", peso: "50 g", calorias: 250 },
  { nome: "Chocolate Twix", quantidade: "1 unidade mini", peso: "21 g", calorias: 102 },
  { nome: "Chocolate Charge", quantidade: "1 unidade", peso: "32 g", calorias: 155 },
  
  { nome: "Filé mignon", calorias: 143 },
  { nome: "Picanha", calorias: 309 },
  { nome: "Alcatra", calorias: 250 },
  { nome: "Coxão mole", calorias: 158 },
  { nome: "Contrafilé", calorias: 250 },
  { nome: "Maminha", calorias: 250 },
  { nome: "Cupim", calorias: 332 },
  { nome: "Fraldinha", calorias: 240 },
  { nome: "Patinho", calorias: 140 },
  { nome: "Largato", calorias: 128 },
  { nome: "Acém", calorias: 212 },
  { nome: "Costela", calorias: 337 },
  { nome: "Lombo", calorias: 195 },
  { nome: "Pernil", calorias: 136 },
  { nome: "Bacon", calorias: 541 },
  { nome: "Presunto", calorias: 107 },
  { nome: "Frango assado", calorias: 237 },
  { nome: "Frango grelhado", calorias: 240 },
  { nome: "Frango frito - fritadeira elétrica", calorias: 216 },
  { nome: "Frango frito - óleo", calorias: 216 },
  { nome: "Bisteca", calorias: 291 },
  { nome: "Linguiça", calorias: 301 },
  { nome: "Cordeiro", calorias: 294 },
  { nome: "Frango", calorias: 165 },
  { nome: "Peito de frango", calorias: 165 },
  { nome: "Coxa de frango", calorias: 172 },
  { nome: "Sobrecoxa de frango", calorias: 213 },
  { nome: "Asa de frango", calorias: 203 },
  { nome: "Peixe", calorias: 105 },
  { nome: "Salmão", calorias: 206 },
  { nome: "Atum", calorias: 116 },
  { nome: "Bacalhau", calorias: 105 },
  { nome: "Bisnaguinha 'Seven Boys'", calorias: 59 },
  { nome: "Ciabatta", calorias: 247 },
  { nome: "Croissant de queijo", calorias: 328 },
  { nome: "Croissant simples", calorias: 276 },
  { nome: "Pão alemão", calorias: 125 },
  { nome: "Pão com canela e passas", calorias: 71 },
  { nome: "Pão de alho na brasa", calorias: 187 },
  { nome: "Pão de batata simples", calorias: 137 },
  { nome: "Pão de centeio", calorias: 61 },
  { nome: "Pão de coco", calorias: 159 },
  { nome: "Pão de forma", calorias: 62 },
  { nome: "Pão de forma integral linhaça", calorias: 61 },
  { nome: "Pão de forma light", calorias: 36 },
  { nome: "Pão de forma sem casca", calorias: 43 },
  { nome: "Pão de hambúrguer", calorias: 177 },
  { nome: "Pão de hambúrguer com gergelim", calorias: 188 },
  { nome: "Pão de hot dog", calorias: 133 },
  { nome: "Pão de milho", calorias: 120 },
  { nome: "Pão de soja light", calorias: 49 },
  { nome: "Pão francês", calorias: 135 },
  { nome: "Pão francês integral", calorias: 135 },
  { nome: "Pão francês sem miolo", calorias: 75 },
  { nome: "Pão integral sem casca light", calorias: 29 },
  { nome: "Pão italiano", calorias: 137 },
  { nome: "Pão preto", calorias: 70 },
  { nome: "Pão sírio", calorias: 180 },
  { nome: "Pão sovado", calorias: 156 },
  { nome: "Pão de queijo", calorias: 273 }

]  


let contadorCampos = 1;
  
  function autocompletar(campoNumero) {
    const inputCampo = document.getElementById(`alimento${campoNumero}`);
    const textoDigitado = inputCampo.value.toLowerCase();
    const divSugestoes = document.getElementById(`divSugestoes${campoNumero}`);
  
    // Limpar sugestões anteriores
    divSugestoes.innerHTML = "";
  
    // Filtrar as sugestões com base no texto digitado
    const sugestoes = alimentos.filter((alimento) =>
      alimento.nome.toLowerCase().startsWith(textoDigitado)
    );
  
    // Adicionar as sugestões à div de sugestões
    sugestoes.forEach((sugestao) => {
      const sugestaoElemento = document.createElement("div");
      sugestaoElemento.textContent = sugestao.nome;
      sugestaoElemento.addEventListener("click", function () {
        inputCampo.value = sugestao.nome;
        divSugestoes.style.display = "none";
      });
      divSugestoes.appendChild(sugestaoElemento);
    });
  
    // Exibir a div de sugestões
    divSugestoes.style.display = sugestoes.length > 0 ? "block" : "none";
  }
  
  (function () {
    function adicionarCampo() {
      contadorCampos++;
  
      const divCampos = document.getElementById("camposExtras");
  
      const label = document.createElement("label");
      label.setAttribute("for", `alimento${contadorCampos}`);
  
      const input = document.createElement("input");
      input.setAttribute("type", "text");
      input.setAttribute("id", `alimento${contadorCampos}`);
      input.setAttribute("class", "campoAutocompletar");
      input.setAttribute("required", true);
      input.setAttribute("oninput", `autocompletar(${contadorCampos})`);
  
      const divSugestoes = document.createElement("div");
      divSugestoes.setAttribute("id", `divSugestoes${contadorCampos}`);
      divSugestoes.setAttribute("class", "sugestoes");
      divSugestoes.style.display = "none";
  
      divCampos.appendChild(label);
      divCampos.appendChild(input);
      divCampos.appendChild(divSugestoes);
    }
  
    function resetarFormulario() {
      const inputs = document.querySelectorAll("#caloriasForm input[type='text']");
      const resultado = document.getElementById("resultado");
      resultado.innerText = "";
  
      inputs.forEach((input) => {
        input.value = "";
      });
  
      const divCamposExtras = document.getElementById("camposExtras");
      divCamposExtras.innerHTML = ""; // Limpa todos os campos extras
      contadorCampos = 1; // Redefine o número de campos extras para 1
    }
  
    window.adicionarCampo = adicionarCampo;
    window.resetarFormulario = resetarFormulario;
  })();
  
  function formatarTexto(texto) {
    return texto.toLowerCase().replace(/[.,#!$%^&*;:{}=\-_`~()]/g, "").replace(/\b\w/g, (match) => match.toUpperCase());
  }
  
  function buscarCalorias(alimento) {
    const alimentoEncontrado = alimentos.find((f) => formatarTexto(f.nome) === formatarTexto(alimento));
    return alimentoEncontrado;
  }
  
  function calcularCalorias() {
    const inputs = document.querySelectorAll("#caloriasForm input[type='text']");
    const resultado = document.getElementById("resultado");
    resultado.innerText = "";
  
    let totalCalorias = 0;
  
    inputs.forEach((input) => {
      const alimento = input.value;
      const alimentoEncontrado = buscarCalorias(alimento);
  
      if (alimentoEncontrado) {
        const calorias = alimentoEncontrado.calorias;
        totalCalorias += calorias;
      }
    });
  
    resultado.innerText = `Total de calorias: ${totalCalorias} calorias`;
  }
  

  function mostrarUnidadeDeMedida(alimentoSelecionado) {

    for (const alimento of alimentos) {
      if (alimento[0] === alimentoSelecionado) {
        console.log(`Unidade de medida para ${alimentoSelecionado}: ${alimento[1]}`);
        return;
      }
    }
  
  mostrarUnidadeDeMedida(alimentoSelecionado);
  }