window.alimentos = alimentos;

const alimentos= [

    { nome: "Abacate", calorias: 160 },
    { nome: "Abacaxi", calorias: 50 },
    { nome: "Ameixa", calorias: 46 },
    { nome: "Banana", calorias: 89 },
    { nome: "Cereja", calorias: 50 },
    { nome: "Coco", calorias: 354 },
    { nome: "Damasco", calorias: 48 },
    { nome: "Framboesa", calorias: 52 },
    { nome: "Goiaba", calorias: 68 },
    { nome: "Kiwi", calorias: 61 },
    { nome: "Laranja", calorias: 47 },
    { nome: "Limão", calorias: 29 },
    { nome: "Maçã", calorias: 52 },
    { nome: "Manga", calorias: 60 },
    { nome: "Maracujá", calorias: 97 },
    { nome: "Melancia", calorias: 30 },
    { nome: "Melão", calorias: 34 },
    { nome: "Morango", calorias: 32 },
    { nome: "Pêra", calorias: 57 },
    { nome: "Pêssego", calorias: 39 },   
    { nome: "Filé mignon", calorias: 143 },
    { nome: "Picanha", calorias: 309 },
    { nome: "Alcatra", calorias: 250 },
    { nome: "Coxão mole", calorias: 158 },
    { nome: "Contrafilé", calorias: 250 },
    { nome: "Maminha", calorias: 250 },
    { nome: "Cupim", calorias: 332 },
    { nome: "Fraldinha", calorias: 240 },
    { nome: "Patinho", calorias: 140 },
    { nome: "Largato", calorias: 128 },
    { nome: "Acém", calorias: 212 },
    { nome: "Costela", calorias: 337 },
    { nome: "Lombo", calorias: 195 },
    { nome: "Pernil", calorias: 136 },
    { nome: "Bacon", calorias: 541 },
    { nome: "Presunto", calorias: 107 },
    { nome: "Frango assado", calorias: 237 },
    { nome: "Frango grelhado", calorias: 240 },
    { nome: "Frango frito - fritadeira elétrica", calorias: 216 },
    { nome: "Frango frito - óleo", calorias: 216 },
    { nome: "Bisteca", calorias: 291 },
    { nome: "Linguiça", calorias: 301 },
    { nome: "Cordeiro", calorias: 294 },
    { nome: "Frango", calorias: 165 },
    { nome: "Peito de frango", calorias: 165 },
    { nome: "Coxa de frango", calorias: 172 },
    { nome: "Sobrecoxa de frango", calorias: 213 },
    { nome: "Asa de frango", calorias: 203 },
    { nome: "Peixe", calorias: 105 },
    { nome: "Salmão", calorias: 206 },
    { nome: "Atum", calorias: 116 },
    { nome: "Bacalhau", calorias: 105 },
    { nome: "Bisnaguinha 'Seven Boys'", calorias: 59 },
    { nome: "Ciabatta", calorias: 247 },
    { nome: "Croissant de queijo", calorias: 328 },
    { nome: "Croissant simples", calorias: 276 },
    { nome: "Pão alemão", calorias: 125 },
    { nome: "Pão com canela e passas", calorias: 71 },
    { nome: "Pão de alho na brasa", calorias: 187 },
    { nome: "Pão de batata simples", calorias: 137 },
    { nome: "Pão de centeio", calorias: 61 },
    { nome: "Pão de coco", calorias: 159 },
    { nome: "Pão de forma", calorias: 62 },
    { nome: "Pão de forma integral linhaça", calorias: 61 },
    { nome: "Pão de forma light", calorias: 36 },
    { nome: "Pão de forma sem casca", calorias: 43 },
    { nome: "Pão de hambúrguer", calorias: 177 },
    { nome: "Pão de hambúrguer com gergelim", calorias: 188 },
    { nome: "Pão de hot dog", calorias: 133 },
    { nome: "Pão de milho", calorias: 120 },
    { nome: "Pão de soja light", calorias: 49 },
    { nome: "Pão francês", calorias: 135 },
    { nome: "Pão francês integral", calorias: 135 },
    { nome: "Pão francês sem miolo", calorias: 75 },
    { nome: "Pão integral sem casca light", calorias: 29 },
    { nome: "Pão italiano", calorias: 137 },
    { nome: "Pão preto", calorias: 70 },
    { nome: "Pão sírio", calorias: 180 },
    { nome: "Pão sovado", calorias: 156 },
    { nome: "Pão de queijo", calorias: 273 }
  
  ]  
  